version: '3'

vars:
  APP_NAME: Comigo
  BIN_DIR: bin

tasks:
  build:
    summary: 构建当前平台 Wails3 二进制。
    cmds:
      - task: "{{OS}}:build"

  run:
    summary: 运行当前平台 Wails3 二进制。
    cmds:
      - task: "{{OS}}:run"

  darwin:build:
    summary: 构建 macOS Wails3 二进制。
    platforms: [darwin]
    cmds:
      - mkdir -p "{{.BIN_DIR}}"
      - templ generate
      - bun run {{.FRONTEND_COMMAND}}
      - go build {{.BUILD_FLAGS}} -o "{{.BIN_DIR}}/{{.APP_NAME}}"
    vars:
      TAGS: '{{.EXTRA_TAGS | default "wails"}}'
      FRONTEND_COMMAND: '{{if eq .DEV "true"}}dev{{else}}build{{end}}'
      BUILD_FLAGS: '{{if eq .DEV "true"}}-tags {{.TAGS}} -buildvcs=false -gcflags=all="-l"{{else}}-tags production,{{.TAGS}} -trimpath -buildvcs=false -ldflags="-w -s"{{end}}'
    env:
      GOOS: darwin
      GOARCH: '{{.ARCH | default ARCH}}'
      CGO_ENABLED: 1
      CGO_CFLAGS: "-mmacosx-version-min=12.0"
      CGO_LDFLAGS: "-mmacosx-version-min=12.0"
      MACOSX_DEPLOYMENT_TARGET: "12.0"

  darwin:run:
    summary: 运行 macOS Wails3 二进制。
    platforms: [darwin]
    cmds:
      - '"{{.BIN_DIR}}/{{.APP_NAME}}"'

  linux:build:
    summary: 构建 Linux Wails3 二进制。
    platforms: [linux]
    cmds:
      - mkdir -p "{{.BIN_DIR}}"
      - templ generate
      - bun run {{.FRONTEND_COMMAND}}
      - go build {{.BUILD_FLAGS}} -o "{{.BIN_DIR}}/{{.APP_NAME}}"
    vars:
      TAGS: '{{.EXTRA_TAGS | default "wails"}}'
      FRONTEND_COMMAND: '{{if eq .DEV "true"}}dev{{else}}build{{end}}'
      BUILD_FLAGS: '{{if eq .DEV "true"}}-tags {{.TAGS}} -buildvcs=false -gcflags=all="-l"{{else}}-tags production,{{.TAGS}} -trimpath -buildvcs=false -ldflags="-w -s"{{end}}'
    env:
      GOOS: linux
      GOARCH: '{{.ARCH | default ARCH}}'
      CGO_ENABLED: 1

  linux:run:
    summary: 运行 Linux Wails3 二进制。
    platforms: [linux]
    cmds:
      - '"{{.BIN_DIR}}/{{.APP_NAME}}"'

  windows:build:
    summary: 构建 Windows Wails3 二进制。
    platforms: [windows]
    cmds:
      - mkdir -p "{{.BIN_DIR}}"
      - templ generate
      - bun run {{.FRONTEND_COMMAND}}
      - go build {{.BUILD_FLAGS}} -o "{{.BIN_DIR}}/{{.APP_NAME}}.exe"
    vars:
      TAGS: '{{.EXTRA_TAGS | default "wails"}}'
      FRONTEND_COMMAND: '{{if eq .DEV "true"}}dev{{else}}build{{end}}'
      BUILD_FLAGS: '{{if eq .DEV "true"}}-tags {{.TAGS}} -buildvcs=false -gcflags=all="-l"{{else}}-tags production,{{.TAGS}} -trimpath -buildvcs=false -ldflags="-w -s -H windowsgui"{{end}}'
    env:
      GOOS: windows
      GOARCH: '{{.ARCH | default ARCH}}'
      CGO_ENABLED: 1

  windows:run:
    summary: 运行 Windows Wails3 二进制。
    platforms: [windows]
    cmds:
      - '"{{.BIN_DIR}}/{{.APP_NAME}}.exe"'
