// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/yumenaka/comi/ent/runtime.go

const (
	Version = "v0.10.2-0.20220502113020-4ac82f5bb3f0"           // Version of ent codegen.
	Sum     = "h1:qHA4+ANAzDj6BcDLxNgZuzKxFre/RI9r5wwsI2O+1M4=" // Sum of ent codegen.
)
