// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"
)

type Book struct {
	ID               int64
	Title            string
	BookID           string
	Owner            sql.NullString
	BookPath         string
	StoreUrl         string
	Type             string
	ChildBooksNum    sql.NullInt64
	ChildBooksID     sql.NullString
	Depth            sql.NullInt64
	ParentFolder     sql.NullString
	PageCount        sql.NullInt64
	LastReadPage     sql.NullInt64
	FileSize         sql.NullInt64
	Author           sql.NullString
	Isbn             sql.NullString
	Press            sql.NullString
	PublishedAt      sql.NullString
	ExtractPath      sql.NullString
	ModifiedTime     sql.NullTime
	ExtractNum       sql.NullInt64
	BookComplete     sql.NullBool
	InitComplete     sql.NullBool
	NonUtf8zip       sql.NullBool
	ZipTextEncoding  sql.NullString
	CreatedByVersion sql.NullString
	IsRemote         sql.NullBool
	RemoteUrl        sql.NullString
	RemoteBookID     sql.NullString
	RemoteStoreKey   sql.NullString
	RemoteShelfKey   sql.NullString
	RemoteShelfName  sql.NullString
	CoverName        sql.NullString
	CoverPath        sql.NullString
	CoverSize        sql.NullInt64
	CoverModTime     sql.NullTime
	CoverUrl         sql.NullString
	CoverPageNum     sql.NullInt64
	CoverBlurhash    sql.NullString
	CoverHeight      sql.NullInt64
	CoverWidth       sql.NullInt64
	CoverImgType     sql.NullString
	CoverInsertHtml  sql.NullString
	Deleted          sql.NullBool
}

type Bookmark struct {
	ID          int64
	Type        string
	BookID      string
	BookStoreID sql.NullString
	PageIndex   int64
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type PageInfo struct {
	ID         int64
	BookID     string
	Name       string
	Path       sql.NullString
	Size       sql.NullInt64
	ModTime    sql.NullTime
	Url        sql.NullString
	PageNum    sql.NullInt64
	Blurhash   sql.NullString
	Height     sql.NullInt64
	Width      sql.NullInt64
	ImgType    sql.NullString
	InsertHtml sql.NullString
}

type ScanFailure struct {
	Key              string
	StoreUrl         string
	FilePath         string
	FileSize         int64
	ModifiedUnixNano int64
	CreatedByVersion string
	FailedAt         time.Time
	Error            string
	IsRemote         bool
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Role      sql.NullString
	Email     sql.NullString
	Key       sql.NullString
	ExpiresAt sql.NullTime
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
