
## go install github.com/cosmtrek/air@latest

# nix develop nixpkgs#aaaaxy ?

# https://github.com/cosmtrek/air/blob/master/air_example.toml
root = "."
tmp_dir = "temp"

[build]
# Array of commands to run before each build
# pre_cmd = ["sh sync_code.sh"]

# Array of commands to run after ^C
# post_cmd = ["echo 'hello air' > post_cmd.txt"]

# Just plain old shell command. You could use `make` as well.
cmd = "go build -o ./temp/comigo ./"

# Binary file yields from `cmd`.
bin = "temp/comigo"

# Customize binary, can setup environment variables when run your app.
full_bin = "COMI_DEBUG_MODE=true COMI_MIN_MEDIA_NUM=2 ./temp/comigo"

# Add additional arguments when running binary (bin/full_bin). Will run './tmp/comigo ../'.
args_bin = [ "../../test"]


# Watch these filename extensions.
include_ext = ["go", "rar", "zip", "cbr", "cbz", "tpl", "tmpl", "html"]
# Ignore these filename extensions or directories.
exclude_dir = ["temp", ".idea", ".git", ".vscode", ".cache"]
# Watch these directories if you specified.
include_dir = []
# Exclude files.
exclude_file = ["_test.go", ]
# Exclude unchanged files.
exclude_unchanged = false
# Follow symlink for directories
follow_symlink = false
# This log file places in your tmp_dir.
log = "build-errors.log"
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
kill_delay = "0s"
poll = false
poll_interval = 0

# Rerun binary or not
rerun = true
rerun_delay = 1500
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

# Enable live-reloading on the browser.
[proxy]
enabled = true
proxy_port = 12345
app_port = 1234