// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yumenaka/comi/ent/book"
	"github.com/yumenaka/comi/ent/predicate"
	"github.com/yumenaka/comi/ent/singlepageinfo"
)

// BookUpdate is the builder for updating Book entities.
type BookUpdate struct {
	config
	hooks    []Hook
	mutation *BookMutation
}

// Where appends a list predicates to the BookUpdate builder.
func (bu *BookUpdate) Where(ps ...predicate.Book) *BookUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetName sets the "Name" field.
func (bu *BookUpdate) SetName(s string) *BookUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetBookID sets the "BookID" field.
func (bu *BookUpdate) SetBookID(s string) *BookUpdate {
	bu.mutation.SetBookID(s)
	return bu
}

// SetOwner sets the "Owner" field.
func (bu *BookUpdate) SetOwner(i int) *BookUpdate {
	bu.mutation.ResetOwner()
	bu.mutation.SetOwner(i)
	return bu
}

// AddOwner adds i to the "Owner" field.
func (bu *BookUpdate) AddOwner(i int) *BookUpdate {
	bu.mutation.AddOwner(i)
	return bu
}

// SetFilePath sets the "FilePath" field.
func (bu *BookUpdate) SetFilePath(s string) *BookUpdate {
	bu.mutation.SetFilePath(s)
	return bu
}

// SetBookStorePath sets the "BookStorePath" field.
func (bu *BookUpdate) SetBookStorePath(s string) *BookUpdate {
	bu.mutation.SetBookStorePath(s)
	return bu
}

// SetType sets the "Type" field.
func (bu *BookUpdate) SetType(s string) *BookUpdate {
	bu.mutation.SetType(s)
	return bu
}

// SetChildBookNum sets the "ChildBookNum" field.
func (bu *BookUpdate) SetChildBookNum(i int) *BookUpdate {
	bu.mutation.ResetChildBookNum()
	bu.mutation.SetChildBookNum(i)
	return bu
}

// AddChildBookNum adds i to the "ChildBookNum" field.
func (bu *BookUpdate) AddChildBookNum(i int) *BookUpdate {
	bu.mutation.AddChildBookNum(i)
	return bu
}

// SetDepth sets the "Depth" field.
func (bu *BookUpdate) SetDepth(i int) *BookUpdate {
	bu.mutation.ResetDepth()
	bu.mutation.SetDepth(i)
	return bu
}

// AddDepth adds i to the "Depth" field.
func (bu *BookUpdate) AddDepth(i int) *BookUpdate {
	bu.mutation.AddDepth(i)
	return bu
}

// SetParentFolder sets the "ParentFolder" field.
func (bu *BookUpdate) SetParentFolder(s string) *BookUpdate {
	bu.mutation.SetParentFolder(s)
	return bu
}

// SetAllPageNum sets the "AllPageNum" field.
func (bu *BookUpdate) SetAllPageNum(i int) *BookUpdate {
	bu.mutation.ResetAllPageNum()
	bu.mutation.SetAllPageNum(i)
	return bu
}

// AddAllPageNum adds i to the "AllPageNum" field.
func (bu *BookUpdate) AddAllPageNum(i int) *BookUpdate {
	bu.mutation.AddAllPageNum(i)
	return bu
}

// SetFileSize sets the "FileSize" field.
func (bu *BookUpdate) SetFileSize(i int64) *BookUpdate {
	bu.mutation.ResetFileSize()
	bu.mutation.SetFileSize(i)
	return bu
}

// AddFileSize adds i to the "FileSize" field.
func (bu *BookUpdate) AddFileSize(i int64) *BookUpdate {
	bu.mutation.AddFileSize(i)
	return bu
}

// SetAuthors sets the "Authors" field.
func (bu *BookUpdate) SetAuthors(s string) *BookUpdate {
	bu.mutation.SetAuthors(s)
	return bu
}

// SetISBN sets the "ISBN" field.
func (bu *BookUpdate) SetISBN(s string) *BookUpdate {
	bu.mutation.SetISBN(s)
	return bu
}

// SetPress sets the "Press" field.
func (bu *BookUpdate) SetPress(s string) *BookUpdate {
	bu.mutation.SetPress(s)
	return bu
}

// SetPublishedAt sets the "PublishedAt" field.
func (bu *BookUpdate) SetPublishedAt(s string) *BookUpdate {
	bu.mutation.SetPublishedAt(s)
	return bu
}

// SetExtractPath sets the "ExtractPath" field.
func (bu *BookUpdate) SetExtractPath(s string) *BookUpdate {
	bu.mutation.SetExtractPath(s)
	return bu
}

// SetModified sets the "Modified" field.
func (bu *BookUpdate) SetModified(t time.Time) *BookUpdate {
	bu.mutation.SetModified(t)
	return bu
}

// SetNillableModified sets the "Modified" field if the given value is not nil.
func (bu *BookUpdate) SetNillableModified(t *time.Time) *BookUpdate {
	if t != nil {
		bu.SetModified(*t)
	}
	return bu
}

// SetExtractNum sets the "ExtractNum" field.
func (bu *BookUpdate) SetExtractNum(i int) *BookUpdate {
	bu.mutation.ResetExtractNum()
	bu.mutation.SetExtractNum(i)
	return bu
}

// AddExtractNum adds i to the "ExtractNum" field.
func (bu *BookUpdate) AddExtractNum(i int) *BookUpdate {
	bu.mutation.AddExtractNum(i)
	return bu
}

// SetInitComplete sets the "InitComplete" field.
func (bu *BookUpdate) SetInitComplete(b bool) *BookUpdate {
	bu.mutation.SetInitComplete(b)
	return bu
}

// SetReadPercent sets the "ReadPercent" field.
func (bu *BookUpdate) SetReadPercent(f float64) *BookUpdate {
	bu.mutation.ResetReadPercent()
	bu.mutation.SetReadPercent(f)
	return bu
}

// AddReadPercent adds f to the "ReadPercent" field.
func (bu *BookUpdate) AddReadPercent(f float64) *BookUpdate {
	bu.mutation.AddReadPercent(f)
	return bu
}

// SetNonUTF8Zip sets the "NonUTF8Zip" field.
func (bu *BookUpdate) SetNonUTF8Zip(b bool) *BookUpdate {
	bu.mutation.SetNonUTF8Zip(b)
	return bu
}

// SetZipTextEncoding sets the "ZipTextEncoding" field.
func (bu *BookUpdate) SetZipTextEncoding(s string) *BookUpdate {
	bu.mutation.SetZipTextEncoding(s)
	return bu
}

// AddPageInfoIDs adds the "PageInfos" edge to the SinglePageInfo entity by IDs.
func (bu *BookUpdate) AddPageInfoIDs(ids ...int) *BookUpdate {
	bu.mutation.AddPageInfoIDs(ids...)
	return bu
}

// AddPageInfos adds the "PageInfos" edges to the SinglePageInfo entity.
func (bu *BookUpdate) AddPageInfos(s ...*SinglePageInfo) *BookUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return bu.AddPageInfoIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (bu *BookUpdate) Mutation() *BookMutation {
	return bu.mutation
}

// ClearPageInfos clears all "PageInfos" edges to the SinglePageInfo entity.
func (bu *BookUpdate) ClearPageInfos() *BookUpdate {
	bu.mutation.ClearPageInfos()
	return bu
}

// RemovePageInfoIDs removes the "PageInfos" edge to SinglePageInfo entities by IDs.
func (bu *BookUpdate) RemovePageInfoIDs(ids ...int) *BookUpdate {
	bu.mutation.RemovePageInfoIDs(ids...)
	return bu
}

// RemovePageInfos removes "PageInfos" edges to SinglePageInfo entities.
func (bu *BookUpdate) RemovePageInfos(s ...*SinglePageInfo) *BookUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return bu.RemovePageInfoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BookUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, BookMutation](ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BookUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BookUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BookUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BookUpdate) check() error {
	if v, ok := bu.mutation.Name(); ok {
		if err := book.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "Book.Name": %w`, err)}
		}
	}
	if v, ok := bu.mutation.ChildBookNum(); ok {
		if err := book.ChildBookNumValidator(v); err != nil {
			return &ValidationError{Name: "ChildBookNum", err: fmt.Errorf(`ent: validator failed for field "Book.ChildBookNum": %w`, err)}
		}
	}
	if v, ok := bu.mutation.Depth(); ok {
		if err := book.DepthValidator(v); err != nil {
			return &ValidationError{Name: "Depth", err: fmt.Errorf(`ent: validator failed for field "Book.Depth": %w`, err)}
		}
	}
	if v, ok := bu.mutation.AllPageNum(); ok {
		if err := book.AllPageNumValidator(v); err != nil {
			return &ValidationError{Name: "AllPageNum", err: fmt.Errorf(`ent: validator failed for field "Book.AllPageNum": %w`, err)}
		}
	}
	return nil
}

func (bu *BookUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(book.FieldName, field.TypeString, value)
	}
	if value, ok := bu.mutation.BookID(); ok {
		_spec.SetField(book.FieldBookID, field.TypeString, value)
	}
	if value, ok := bu.mutation.Owner(); ok {
		_spec.SetField(book.FieldOwner, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedOwner(); ok {
		_spec.AddField(book.FieldOwner, field.TypeInt, value)
	}
	if value, ok := bu.mutation.FilePath(); ok {
		_spec.SetField(book.FieldFilePath, field.TypeString, value)
	}
	if value, ok := bu.mutation.BookStorePath(); ok {
		_spec.SetField(book.FieldBookStorePath, field.TypeString, value)
	}
	if value, ok := bu.mutation.GetType(); ok {
		_spec.SetField(book.FieldType, field.TypeString, value)
	}
	if value, ok := bu.mutation.ChildBookNum(); ok {
		_spec.SetField(book.FieldChildBookNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedChildBookNum(); ok {
		_spec.AddField(book.FieldChildBookNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.Depth(); ok {
		_spec.SetField(book.FieldDepth, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedDepth(); ok {
		_spec.AddField(book.FieldDepth, field.TypeInt, value)
	}
	if value, ok := bu.mutation.ParentFolder(); ok {
		_spec.SetField(book.FieldParentFolder, field.TypeString, value)
	}
	if value, ok := bu.mutation.AllPageNum(); ok {
		_spec.SetField(book.FieldAllPageNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedAllPageNum(); ok {
		_spec.AddField(book.FieldAllPageNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.FileSize(); ok {
		_spec.SetField(book.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.AddedFileSize(); ok {
		_spec.AddField(book.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := bu.mutation.Authors(); ok {
		_spec.SetField(book.FieldAuthors, field.TypeString, value)
	}
	if value, ok := bu.mutation.ISBN(); ok {
		_spec.SetField(book.FieldISBN, field.TypeString, value)
	}
	if value, ok := bu.mutation.Press(); ok {
		_spec.SetField(book.FieldPress, field.TypeString, value)
	}
	if value, ok := bu.mutation.PublishedAt(); ok {
		_spec.SetField(book.FieldPublishedAt, field.TypeString, value)
	}
	if value, ok := bu.mutation.ExtractPath(); ok {
		_spec.SetField(book.FieldExtractPath, field.TypeString, value)
	}
	if value, ok := bu.mutation.Modified(); ok {
		_spec.SetField(book.FieldModified, field.TypeTime, value)
	}
	if value, ok := bu.mutation.ExtractNum(); ok {
		_spec.SetField(book.FieldExtractNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedExtractNum(); ok {
		_spec.AddField(book.FieldExtractNum, field.TypeInt, value)
	}
	if value, ok := bu.mutation.InitComplete(); ok {
		_spec.SetField(book.FieldInitComplete, field.TypeBool, value)
	}
	if value, ok := bu.mutation.ReadPercent(); ok {
		_spec.SetField(book.FieldReadPercent, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.AddedReadPercent(); ok {
		_spec.AddField(book.FieldReadPercent, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.NonUTF8Zip(); ok {
		_spec.SetField(book.FieldNonUTF8Zip, field.TypeBool, value)
	}
	if value, ok := bu.mutation.ZipTextEncoding(); ok {
		_spec.SetField(book.FieldZipTextEncoding, field.TypeString, value)
	}
	if bu.mutation.PageInfosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.RemovedPageInfosIDs(); len(nodes) > 0 && !bu.mutation.PageInfosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.PageInfosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BookUpdateOne is the builder for updating a single Book entity.
type BookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BookMutation
}

// SetName sets the "Name" field.
func (buo *BookUpdateOne) SetName(s string) *BookUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetBookID sets the "BookID" field.
func (buo *BookUpdateOne) SetBookID(s string) *BookUpdateOne {
	buo.mutation.SetBookID(s)
	return buo
}

// SetOwner sets the "Owner" field.
func (buo *BookUpdateOne) SetOwner(i int) *BookUpdateOne {
	buo.mutation.ResetOwner()
	buo.mutation.SetOwner(i)
	return buo
}

// AddOwner adds i to the "Owner" field.
func (buo *BookUpdateOne) AddOwner(i int) *BookUpdateOne {
	buo.mutation.AddOwner(i)
	return buo
}

// SetFilePath sets the "FilePath" field.
func (buo *BookUpdateOne) SetFilePath(s string) *BookUpdateOne {
	buo.mutation.SetFilePath(s)
	return buo
}

// SetBookStorePath sets the "BookStorePath" field.
func (buo *BookUpdateOne) SetBookStorePath(s string) *BookUpdateOne {
	buo.mutation.SetBookStorePath(s)
	return buo
}

// SetType sets the "Type" field.
func (buo *BookUpdateOne) SetType(s string) *BookUpdateOne {
	buo.mutation.SetType(s)
	return buo
}

// SetChildBookNum sets the "ChildBookNum" field.
func (buo *BookUpdateOne) SetChildBookNum(i int) *BookUpdateOne {
	buo.mutation.ResetChildBookNum()
	buo.mutation.SetChildBookNum(i)
	return buo
}

// AddChildBookNum adds i to the "ChildBookNum" field.
func (buo *BookUpdateOne) AddChildBookNum(i int) *BookUpdateOne {
	buo.mutation.AddChildBookNum(i)
	return buo
}

// SetDepth sets the "Depth" field.
func (buo *BookUpdateOne) SetDepth(i int) *BookUpdateOne {
	buo.mutation.ResetDepth()
	buo.mutation.SetDepth(i)
	return buo
}

// AddDepth adds i to the "Depth" field.
func (buo *BookUpdateOne) AddDepth(i int) *BookUpdateOne {
	buo.mutation.AddDepth(i)
	return buo
}

// SetParentFolder sets the "ParentFolder" field.
func (buo *BookUpdateOne) SetParentFolder(s string) *BookUpdateOne {
	buo.mutation.SetParentFolder(s)
	return buo
}

// SetAllPageNum sets the "AllPageNum" field.
func (buo *BookUpdateOne) SetAllPageNum(i int) *BookUpdateOne {
	buo.mutation.ResetAllPageNum()
	buo.mutation.SetAllPageNum(i)
	return buo
}

// AddAllPageNum adds i to the "AllPageNum" field.
func (buo *BookUpdateOne) AddAllPageNum(i int) *BookUpdateOne {
	buo.mutation.AddAllPageNum(i)
	return buo
}

// SetFileSize sets the "FileSize" field.
func (buo *BookUpdateOne) SetFileSize(i int64) *BookUpdateOne {
	buo.mutation.ResetFileSize()
	buo.mutation.SetFileSize(i)
	return buo
}

// AddFileSize adds i to the "FileSize" field.
func (buo *BookUpdateOne) AddFileSize(i int64) *BookUpdateOne {
	buo.mutation.AddFileSize(i)
	return buo
}

// SetAuthors sets the "Authors" field.
func (buo *BookUpdateOne) SetAuthors(s string) *BookUpdateOne {
	buo.mutation.SetAuthors(s)
	return buo
}

// SetISBN sets the "ISBN" field.
func (buo *BookUpdateOne) SetISBN(s string) *BookUpdateOne {
	buo.mutation.SetISBN(s)
	return buo
}

// SetPress sets the "Press" field.
func (buo *BookUpdateOne) SetPress(s string) *BookUpdateOne {
	buo.mutation.SetPress(s)
	return buo
}

// SetPublishedAt sets the "PublishedAt" field.
func (buo *BookUpdateOne) SetPublishedAt(s string) *BookUpdateOne {
	buo.mutation.SetPublishedAt(s)
	return buo
}

// SetExtractPath sets the "ExtractPath" field.
func (buo *BookUpdateOne) SetExtractPath(s string) *BookUpdateOne {
	buo.mutation.SetExtractPath(s)
	return buo
}

// SetModified sets the "Modified" field.
func (buo *BookUpdateOne) SetModified(t time.Time) *BookUpdateOne {
	buo.mutation.SetModified(t)
	return buo
}

// SetNillableModified sets the "Modified" field if the given value is not nil.
func (buo *BookUpdateOne) SetNillableModified(t *time.Time) *BookUpdateOne {
	if t != nil {
		buo.SetModified(*t)
	}
	return buo
}

// SetExtractNum sets the "ExtractNum" field.
func (buo *BookUpdateOne) SetExtractNum(i int) *BookUpdateOne {
	buo.mutation.ResetExtractNum()
	buo.mutation.SetExtractNum(i)
	return buo
}

// AddExtractNum adds i to the "ExtractNum" field.
func (buo *BookUpdateOne) AddExtractNum(i int) *BookUpdateOne {
	buo.mutation.AddExtractNum(i)
	return buo
}

// SetInitComplete sets the "InitComplete" field.
func (buo *BookUpdateOne) SetInitComplete(b bool) *BookUpdateOne {
	buo.mutation.SetInitComplete(b)
	return buo
}

// SetReadPercent sets the "ReadPercent" field.
func (buo *BookUpdateOne) SetReadPercent(f float64) *BookUpdateOne {
	buo.mutation.ResetReadPercent()
	buo.mutation.SetReadPercent(f)
	return buo
}

// AddReadPercent adds f to the "ReadPercent" field.
func (buo *BookUpdateOne) AddReadPercent(f float64) *BookUpdateOne {
	buo.mutation.AddReadPercent(f)
	return buo
}

// SetNonUTF8Zip sets the "NonUTF8Zip" field.
func (buo *BookUpdateOne) SetNonUTF8Zip(b bool) *BookUpdateOne {
	buo.mutation.SetNonUTF8Zip(b)
	return buo
}

// SetZipTextEncoding sets the "ZipTextEncoding" field.
func (buo *BookUpdateOne) SetZipTextEncoding(s string) *BookUpdateOne {
	buo.mutation.SetZipTextEncoding(s)
	return buo
}

// AddPageInfoIDs adds the "PageInfos" edge to the SinglePageInfo entity by IDs.
func (buo *BookUpdateOne) AddPageInfoIDs(ids ...int) *BookUpdateOne {
	buo.mutation.AddPageInfoIDs(ids...)
	return buo
}

// AddPageInfos adds the "PageInfos" edges to the SinglePageInfo entity.
func (buo *BookUpdateOne) AddPageInfos(s ...*SinglePageInfo) *BookUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return buo.AddPageInfoIDs(ids...)
}

// Mutation returns the BookMutation object of the builder.
func (buo *BookUpdateOne) Mutation() *BookMutation {
	return buo.mutation
}

// ClearPageInfos clears all "PageInfos" edges to the SinglePageInfo entity.
func (buo *BookUpdateOne) ClearPageInfos() *BookUpdateOne {
	buo.mutation.ClearPageInfos()
	return buo
}

// RemovePageInfoIDs removes the "PageInfos" edge to SinglePageInfo entities by IDs.
func (buo *BookUpdateOne) RemovePageInfoIDs(ids ...int) *BookUpdateOne {
	buo.mutation.RemovePageInfoIDs(ids...)
	return buo
}

// RemovePageInfos removes "PageInfos" edges to SinglePageInfo entities.
func (buo *BookUpdateOne) RemovePageInfos(s ...*SinglePageInfo) *BookUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return buo.RemovePageInfoIDs(ids...)
}

// Where appends a list predicates to the BookUpdate builder.
func (buo *BookUpdateOne) Where(ps ...predicate.Book) *BookUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BookUpdateOne) Select(field string, fields ...string) *BookUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Book entity.
func (buo *BookUpdateOne) Save(ctx context.Context) (*Book, error) {
	return withHooks[*Book, BookMutation](ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BookUpdateOne) SaveX(ctx context.Context) *Book {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BookUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BookUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BookUpdateOne) check() error {
	if v, ok := buo.mutation.Name(); ok {
		if err := book.NameValidator(v); err != nil {
			return &ValidationError{Name: "Name", err: fmt.Errorf(`ent: validator failed for field "Book.Name": %w`, err)}
		}
	}
	if v, ok := buo.mutation.ChildBookNum(); ok {
		if err := book.ChildBookNumValidator(v); err != nil {
			return &ValidationError{Name: "ChildBookNum", err: fmt.Errorf(`ent: validator failed for field "Book.ChildBookNum": %w`, err)}
		}
	}
	if v, ok := buo.mutation.Depth(); ok {
		if err := book.DepthValidator(v); err != nil {
			return &ValidationError{Name: "Depth", err: fmt.Errorf(`ent: validator failed for field "Book.Depth": %w`, err)}
		}
	}
	if v, ok := buo.mutation.AllPageNum(); ok {
		if err := book.AllPageNumValidator(v); err != nil {
			return &ValidationError{Name: "AllPageNum", err: fmt.Errorf(`ent: validator failed for field "Book.AllPageNum": %w`, err)}
		}
	}
	return nil
}

func (buo *BookUpdateOne) sqlSave(ctx context.Context) (_node *Book, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(book.Table, book.Columns, sqlgraph.NewFieldSpec(book.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Book.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, book.FieldID)
		for _, f := range fields {
			if !book.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != book.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(book.FieldName, field.TypeString, value)
	}
	if value, ok := buo.mutation.BookID(); ok {
		_spec.SetField(book.FieldBookID, field.TypeString, value)
	}
	if value, ok := buo.mutation.Owner(); ok {
		_spec.SetField(book.FieldOwner, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedOwner(); ok {
		_spec.AddField(book.FieldOwner, field.TypeInt, value)
	}
	if value, ok := buo.mutation.FilePath(); ok {
		_spec.SetField(book.FieldFilePath, field.TypeString, value)
	}
	if value, ok := buo.mutation.BookStorePath(); ok {
		_spec.SetField(book.FieldBookStorePath, field.TypeString, value)
	}
	if value, ok := buo.mutation.GetType(); ok {
		_spec.SetField(book.FieldType, field.TypeString, value)
	}
	if value, ok := buo.mutation.ChildBookNum(); ok {
		_spec.SetField(book.FieldChildBookNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedChildBookNum(); ok {
		_spec.AddField(book.FieldChildBookNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.Depth(); ok {
		_spec.SetField(book.FieldDepth, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedDepth(); ok {
		_spec.AddField(book.FieldDepth, field.TypeInt, value)
	}
	if value, ok := buo.mutation.ParentFolder(); ok {
		_spec.SetField(book.FieldParentFolder, field.TypeString, value)
	}
	if value, ok := buo.mutation.AllPageNum(); ok {
		_spec.SetField(book.FieldAllPageNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedAllPageNum(); ok {
		_spec.AddField(book.FieldAllPageNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.FileSize(); ok {
		_spec.SetField(book.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.AddedFileSize(); ok {
		_spec.AddField(book.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := buo.mutation.Authors(); ok {
		_spec.SetField(book.FieldAuthors, field.TypeString, value)
	}
	if value, ok := buo.mutation.ISBN(); ok {
		_spec.SetField(book.FieldISBN, field.TypeString, value)
	}
	if value, ok := buo.mutation.Press(); ok {
		_spec.SetField(book.FieldPress, field.TypeString, value)
	}
	if value, ok := buo.mutation.PublishedAt(); ok {
		_spec.SetField(book.FieldPublishedAt, field.TypeString, value)
	}
	if value, ok := buo.mutation.ExtractPath(); ok {
		_spec.SetField(book.FieldExtractPath, field.TypeString, value)
	}
	if value, ok := buo.mutation.Modified(); ok {
		_spec.SetField(book.FieldModified, field.TypeTime, value)
	}
	if value, ok := buo.mutation.ExtractNum(); ok {
		_spec.SetField(book.FieldExtractNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedExtractNum(); ok {
		_spec.AddField(book.FieldExtractNum, field.TypeInt, value)
	}
	if value, ok := buo.mutation.InitComplete(); ok {
		_spec.SetField(book.FieldInitComplete, field.TypeBool, value)
	}
	if value, ok := buo.mutation.ReadPercent(); ok {
		_spec.SetField(book.FieldReadPercent, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.AddedReadPercent(); ok {
		_spec.AddField(book.FieldReadPercent, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.NonUTF8Zip(); ok {
		_spec.SetField(book.FieldNonUTF8Zip, field.TypeBool, value)
	}
	if value, ok := buo.mutation.ZipTextEncoding(); ok {
		_spec.SetField(book.FieldZipTextEncoding, field.TypeString, value)
	}
	if buo.mutation.PageInfosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.RemovedPageInfosIDs(); len(nodes) > 0 && !buo.mutation.PageInfosCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.PageInfosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   book.PageInfosTable,
			Columns: []string{book.PageInfosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: singlepageinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Book{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{book.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
