// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yumenaka/comi/ent/singlepageinfo"
)

// SinglePageInfoCreate is the builder for creating a SinglePageInfo entity.
type SinglePageInfoCreate struct {
	config
	mutation *SinglePageInfoMutation
	hooks    []Hook
}

// Mutation returns the SinglePageInfoMutation object of the builder.
func (spic *SinglePageInfoCreate) Mutation() *SinglePageInfoMutation {
	return spic.mutation
}

// Save creates the SinglePageInfo in the database.
func (spic *SinglePageInfoCreate) Save(ctx context.Context) (*SinglePageInfo, error) {
	var (
		err  error
		node *SinglePageInfo
	)
	if len(spic.hooks) == 0 {
		if err = spic.check(); err != nil {
			return nil, err
		}
		node, err = spic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SinglePageInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = spic.check(); err != nil {
				return nil, err
			}
			spic.mutation = mutation
			if node, err = spic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(spic.hooks) - 1; i >= 0; i-- {
			if spic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, spic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (spic *SinglePageInfoCreate) SaveX(ctx context.Context) *SinglePageInfo {
	v, err := spic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (spic *SinglePageInfoCreate) Exec(ctx context.Context) error {
	_, err := spic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spic *SinglePageInfoCreate) ExecX(ctx context.Context) {
	if err := spic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (spic *SinglePageInfoCreate) check() error {
	return nil
}

func (spic *SinglePageInfoCreate) sqlSave(ctx context.Context) (*SinglePageInfo, error) {
	_node, _spec := spic.createSpec()
	if err := sqlgraph.CreateNode(ctx, spic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (spic *SinglePageInfoCreate) createSpec() (*SinglePageInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &SinglePageInfo{config: spic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: singlepageinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: singlepageinfo.FieldID,
			},
		}
	)
	return _node, _spec
}

// SinglePageInfoCreateBulk is the builder for creating many SinglePageInfo entities in bulk.
type SinglePageInfoCreateBulk struct {
	config
	builders []*SinglePageInfoCreate
}

// Save creates the SinglePageInfo entities in the database.
func (spicb *SinglePageInfoCreateBulk) Save(ctx context.Context) ([]*SinglePageInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(spicb.builders))
	nodes := make([]*SinglePageInfo, len(spicb.builders))
	mutators := make([]Mutator, len(spicb.builders))
	for i := range spicb.builders {
		func(i int, root context.Context) {
			builder := spicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SinglePageInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, spicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, spicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, spicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (spicb *SinglePageInfoCreateBulk) SaveX(ctx context.Context) []*SinglePageInfo {
	v, err := spicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (spicb *SinglePageInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := spicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spicb *SinglePageInfoCreateBulk) ExecX(ctx context.Context) {
	if err := spicb.Exec(ctx); err != nil {
		panic(err)
	}
}
