# 既に git 管理しているファイルをあえて無視したい:
# git update-index --assume-unchanged .air.toml
# Undo:
# git update-index --no-assume-unchanged .air.toml
root = "."
tmp_dir = "temp"
testdata_dir = "testdata"

[build]
args_bin = ["../test"]
bin = "./temp/comi"
pre_cmd = ["bun run dev"]
post_cmd = []
cmd = "go run github.com/a-h/templ/cmd/templ@latest generate && go build -o ./temp/comi ."
full_bin = ""
include_ext = ["go", "templ", "html", "json", "js", "ts", "css", "scss"]
exclude_dir = [
    "static/static/",
    ".parcel-cache",
    "bin",
    "dist",
    "node_modules",
    "static",
    "tmp",
    "tests",
    "vendor",
]
exclude_regex = ["_test\\.go", "_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
kill_delay = "0s"
log = "build-errors-air.log"
poll = false
poll_interval = 500
delay = 4000
rerun = true
rerun_delay = 100
send_interrupt = false
stop_on_error = false

[log]
    main_only = false
    silent = false
    time = false
[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = false

[proxy]
enabled = true
proxy_port = 7777
app_port = 1234

[screen]
clear_on_rebuild = false
keep_scroll = true
