// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package common

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ReadModeSwitchButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- 阅读页统一在卷轴阅读和翻页阅读之间切换，本地 reader 不改变 URL。 --><div x-data=\"{\n\t\t\tisReadPage() {\n\t\t\t\tconst pathname = window.ComiGoRelativePath ? window.ComiGoRelativePath(window.location.pathname) : window.location.pathname;\n\t\t\t\tconst firstSegment = pathname.split('/').filter(Boolean)[0];\n\t\t\t\treturn window.ComiGoReaderMode || ($store.global.onlineBook && (firstSegment === 'scroll' || firstSegment === 'flip'));\n\t\t\t},\n\t\t\tswitchReadMode() {\n\t\t\t\tconst nextMode = $store.global.readMode === 'flip' ? 'scroll' : 'flip';\n\t\t\t\tif (window.ComiGoReaderMode) {\n\t\t\t\t\twindow.ComiGoReader?.setReadMode(nextMode);\n\t\t\t\t\treturn;\n\t\t\t\t}\n\t\t\t\t$store.global.readMode = nextMode;\n\t\t\t\t$store.global.onChangeReadMode();\n\t\t\t},\n\t\t\treadModeSwitchText() {\n\t\t\t\tconst isFlip = $store.global.readMode === 'flip';\n\t\t\t\treturn i18next.t(isFlip ? 'switch_scroll_reading' : 'switch_flip_reading', {\n\t\t\t\t\tdefaultValue: isFlip ? '切换卷轴阅读' : '切换翻页阅读',\n\t\t\t\t});\n\t\t\t}\n\t\t}\" x-show=\"isReadPage()\" class=\"flex flex-row justify-center items-center w-full mt-2 mb-2 pb-1 border-2 border-gray-500 dark:border-gray-200 rounded relative\"><!-- 切换 --><span class=\"absolute left-1/2 -translate-x-1/2 top-0 -translate-y-1/2 px-2 bg-base-100 font-semibold text-xs text-base-content\" x-text=\"i18next.t('switch')\">切换</span> <button type=\"button\" class=\"z-10 flex justify-center items-center h-10 px-3 mx-1 mt-2 mb-1 text-sm border rounded text-black font-semibold focus:outline-none focus:ring bg-blue-200 transition delay-150 duration-300 ease-in-out hover:bg-indigo-300\" @click=\"switchReadMode()\" x-text=\"readModeSwitchText()\" x-bind:aria-label=\"readModeSwitchText()\"></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
